### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by DylanBPY** [truckermudgeon/truckermudgeon.github.io#2]
Hello, my name is Dylan, I'm one of the developers from ETS2LA, you may have seen Tumppi066's issue in your other repository. We are really excited to have come across this magnificent project. 

I'm trying to implement RenCloud's TruckSimAPI plugin so that this can act like a GPS. ETS2LA has a route planner very similar to ETS2's which allows us to get (usually) the shortest possible route to a destination, having this for visualization would be absolutely amazing.

One problem though, this code seems to be a compiled version specifically for GitHub Pages, where could I access the actual source code?

I hope you can work with us at ETS2LA to make a great program, as Tumppi said you can join the Discord if you want to chat with us here: [https://discord.com/invite/ets2la](https://discord.com/invite/ets2la).

Thank you for your time!
- Dylan, ETS2LA Dev Team

**Comment by DylanBPY** [comment]
Turns out I'm pretty dumb, the answer was right in front of me the whole time.

**Comment by truckermudgeon** [comment]
> Turns out I'm pretty dumb, the answer was right in front of me the whole time.

You're not; this is on me for not having written a README for this repo... it's been on my TODO list 🫠 

> ETS2LA has a route planner very similar to ETS2's which allows us to get (usually) the shortest possible route to a destination

Cool! Sounds similar to the undocumented (but not for long) [`/routes` demo](https://truckermudgeon.github.io/routes) 😁 

>  you can join the Discord if you want to chat with us here

I'll pop in and say hi 🙂
